# Generated by Django 3.1.2 on 2020-11-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201102_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='description',
        ),
    ]
