# Generated by Django 3.1.2 on 2020-11-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_recipeitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('mg', 'Milligram'), ('kg', 'Kilogram'), ('ml', 'Millimeter'), ('l', 'Liter'), ('oz', 'Oz'), ('us_tbsp', 'Table Spoon'), ('us_tsp', 'Tea Spoon'), ('us_cup', 'Cup')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('mg', 'Milligram'), ('kg', 'Kilogram'), ('ml', 'Millimeter'), ('l', 'Liter'), ('oz', 'Oz'), ('us_tbsp', 'Table Spoon'), ('us_tsp', 'Tea Spoon'), ('us_cup', 'Cup')], max_length=200),
        ),
        migrations.CreateModel(
            name='IngredientConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('mg', 'Milligram'), ('kg', 'Kilogram'), ('ml', 'Millimeter'), ('l', 'Liter'), ('oz', 'Oz'), ('us_tbsp', 'Table Spoon'), ('us_tsp', 'Tea Spoon'), ('us_cup', 'Cup')], max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ingredient')),
            ],
        ),
    ]
